"""                             
_/_/_/_/_/                          _/  _/                _/  _/        _/    
   _/      _/_/    _/  _/_/    _/_/_/        _/_/        _/  _/      _/  _/   
  _/    _/    _/  _/_/      _/    _/  _/  _/_/_/_/      _/_/_/_/    _/  _/    
 _/    _/    _/  _/        _/    _/  _/  _/                _/      _/  _/     
_/      _/_/    _/          _/_/_/  _/    _/_/_/          _/  _/    _/

CC BY-NC-SA: 2022-2023

Tordie 4.0 is an Origami pattern generator with high mathematical functionality
designed to cross the bridge from ideas into practical SVG files to use for scoring.

Developer: Moaesaycto (S.L.)

Title generated by: https://ascii.today/
"""

from init import init
from svg_tools.svg import Diagram
from shapes import Point as P
from shapes import Parametric, MiuraOri
from svg_tools.svg_parser import ImportedSVG
from helpers import  exp
from math import exp as e # Built in maths class
from math import floor, pi

if __name__ == '__main__':
    init(short=False)
    drawing = Diagram()
    imported = ImportedSVG('input.svg', rel_scale="(1u,1u)")
    ori = MiuraOri(4, 24, v_height=2*pi, h_width=2*pi, parametric_verts=True, top=False, squash_factor=1, start=P(2, -pi))
    ori = ori.conformal(imported.generate_circular_mapping())
    drawing.draw(ori)
    drawing.display()
